// Database enums matching the backend schema

export enum Rank {
  UNRANKED = "UNRANKED",
  IRON_1 = "IRON_1",
  IRON_2 = "IRON_2",
  IRON_3 = "IRON_3",
  BRONZE_1 = "BRONZE_1",
  BRONZE_2 = "BRONZE_2",
  BRONZE_3 = "BRONZE_3",
  SILVER_1 = "SILVER_1",
  SILVER_2 = "SILVER_2",
  SILVER_3 = "SILVER_3",
  GOLD_1 = "GOLD_1",
  GOLD_2 = "GOLD_2",
  GOLD_3 = "GOLD_3",
  PLATINUM_1 = "PLATINUM_1",
  PLATINUM_2 = "PLATINUM_2",
  PLATINUM_3 = "PLATINUM_3",
  DIAMOND_1 = "DIAMOND_1",
  DIAMOND_2 = "DIAMOND_2",
  DIAMOND_3 = "DIAMOND_3",
  EMERALD_1 = "EMERALD_1",
  EMERALD_2 = "EMERALD_2",
  EMERALD_3 = "EMERALD_3",
  LAPIS_1 = "LAPIS_1",
  LAPIS_2 = "LAPIS_2",
  LAPIS_3 = "LAPIS_3",
  QUARTZ_1 = "QUARTZ_1",
  QUARTZ_2 = "QUARTZ_2",
  QUARTZ_3 = "QUARTZ_3",
  SAPHIRE_1 = "SAPHIRE_1",
  SAPHIRE_2 = "SAPHIRE_2",
  SAPHIRE_3 = "SAPHIRE_3",
  OBSIDIAN = "OBSIDIAN",
}

export enum Domain {
  FRONTEND = "FRONTEND",
  BACKEND = "BACKEND",
  FULLSTACK = "FULLSTACK",
  SDE_TEST = "SDE_TEST",
  QUALITY_ASSURANCE = "QUALITY_ASSURANCE",
  TEST_AUTOMATION = "TEST_AUTOMATION",
  DEVOPS = "DEVOPS",
  MLOPS = "MLOPS",
  CI_CD = "CI_CD",
  CLOUD = "CLOUD",
  SITE_RELIABILITY = "SITE_RELIABILITY",
  SOFTWARE_INFRASTRUCTURE = "SOFTWARE_INFRASTRUCTURE",
  DISTRIBUTED_SYSTEMS = "DISTRIBUTED_SYSTEMS",
  EMBEDDED_IOT = "EMBEDDED_IOT",
  ML_ENGINEERING = "ML_ENGINEERING",
  ML_RESEARCH = "ML_RESEARCH",
  DATA_SCIENCE_ANALYSIS = "DATA_SCIENCE_ANALYSIS",
  DATA_ENGINEERING = "DATA_ENGINEERING",
  QUANT_ENGINEERING = "QUANT_ENGINEERING",
  ANDROID = "ANDROID",
  IOS = "IOS",
  CROSS_PLATFORM_MOBILE = "CROSS_PLATFORM_MOBILE",
  WINDOWS = "WINDOWS",
  MACOS = "MACOS",
  LINUX = "LINUX",
  CROSS_PLATFORM_PC = "CROSS_PLATFORM_PC",
  COMPUTER_SYSTEMS = "COMPUTER_SYSTEMS",
  COMPILERS = "COMPILERS",
  GAME_DEV = "GAME_DEV",
  APPLICATION_SECURITY = "APPLICATION_SECURITY",
  PLATFORM_SECURITY = "PLATFORM_SECURITY",
  DEVSECOPS = "DEVSECOPS",
  UI_UX = "UI_UX",
  PRODUCT_MANAGEMENT = "PRODUCT_MANAGEMENT",
  PRODUCT_ENGINEERING = "PRODUCT_ENGINEERING",
  TECHNICAL_WRITING = "TECHNICAL_WRITING",
  OTHER = "OTHER",
}

export enum WorkLocationType {
  ON_SITE = "ON_SITE",
  REMOTE = "REMOTE",
  HYBRID = "HYBRID",
}

export enum EmploymentType {
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  SELF_EMPLOYED = "SELF_EMPLOYED",
  FREELANCE = "FREELANCE",
  CONTRACT = "CONTRACT",
  INTERNSHIP = "INTERNSHIP",
  APPRENTICESHIP = "APPRENTICESHIP",
  SEASONAL = "SEASONAL",
}

export enum Tools {
  JAVA = "JAVA",
  C = "C",
  CPP = "CPP",
  PYTHON = "PYTHON",
  CSHARP = "CSHARP",
  RUST = "RUST",
  JAVASCRIPT = "JAVASCRIPT",
  TYPESCRIPT = "TYPESCRIPT",
  GO = "GO",
  GROOVY = "GROOVY",
  RUBY = "RUBY",
  PHP = "PHP",
  SWIFT = "SWIFT",
  REACTJS = "REACTJS",
  ANGULARJS = "ANGULARJS",
  NEXTJS = "NEXTJS",
  VUEJS = "VUEJS",
  SVELTE = "SVELTE",
  NODEJS = "NODEJS",
  DJANGO = "DJANGO",
  FLASK = "FLASK",
  SPRINGBOOT = "SPRINGBOOT",
  GIT = "GIT",
  MARKDOWN = "MARKDOWN",
  DOCKER = "DOCKER",
  KUBERNETES = "KUBERNETES",
  HTML = "HTML",
  CSS = "CSS",
  POSTMAN = "POSTMAN",
  FIREBASE = "FIREBASE",
  SUPABASE = "SUPABASE",
  AWS = "AWS",
  AZURE = "AZURE",
  GCP = "GCP",
  HEROKU = "HEROKU",
  DIGITALOCEAN = "DIGITALOCEAN",
  VERCEL = "VERCEL",
  RAILWAY = "RAILWAY",
  NETLIFY = "NETLIFY",
  JENKINS = "JENKINS",
  REDIS = "REDIS",
  MONGODB = "MONGODB",
  MYSQL = "MYSQL",
  MSSQL = "MSSQL",
  POSTGRESQL = "POSTGRESQL",
  SQLITE = "SQLITE",
  ELASTICSEARCH = "ELASTICSEARCH",
  KAFKA = "KAFKA",
  RABBITMQ = "RABBITMQ",
  GRAPHQL = "GRAPHQL",
  COUCHDB = "COUCHDB",
  CASSANDRA = "CASSANDRA",
}

export enum CertificationType {
  CERTIFICATE = "CERTIFICATE",
  LICENSE = "LICENSE",
  CERTIFICATION = "CERTIFICATION",
}

export enum Role {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  TEAM_LEAD = "TEAM_LEAD",
}

export enum Cause {
  EDUCATION = "EDUCATION",
  ENVIRONMENT = "ENVIRONMENT",
  SOCIAL_CAUSES = "SOCIAL_CAUSES",
  HUMAN_RIGHT = "HUMAN_RIGHT",
  SCIENCE_TECHNOLOGY = "SCIENCE_TECHNOLOGY",
}

export enum LeetcodeTagCategory {
  FUNDAMENTAL = "FUNDAMENTAL",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
}

export enum Currency {
  INR = "INR",
  USD = "USD",
  CHF = "CHF",
  EUR = "EUR",
  AUD = "AUD",
  SGD = "SGD",
  GBP = "GBP",
}

export enum ProjectLevel {
  USER_PROJECT = "USER_PROJECT",
  DIJKSTRA_PROJECT = "DIJKSTRA_PROJECT",
  DIJKSTRA_AFFILIATE_PROJECT = "DIJKSTRA_AFFILIATE_PROJECT",
  OS_FRIENDLY_PROJECTS = "OS_FRIENDLY_PROJECTS",
  OS_HARD_PROJECTS = "OS_HARD_PROJECTS",
}

export enum Difficulty {
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD",
  EXTREME = "EXTREME",
}

export enum Status {
  TODO = "TODO",
  IN_PROGRESS = "IN_PROGRESS",
  DONE = "DONE",
  BACKLOG = "BACKLOG",
  BLOCKED = "BLOCKED",
  OTHER = "OTHER",
}

export enum TestScoreType {
  GRE = "GRE",
  GMAT = "GMAT",
  CGPA = "CGPA",
  TENTH = "TENTH",
  TWELFTH = "TWELFTH",
}

export enum SchoolType {
  UNIVERSITY = "UNIVERSITY",
  COLLEGE = "COLLEGE",
  SCHOOL = "SCHOOL",
  COURSE = "COURSE",
  BOOTCAMP = "BOOTCAMP",
  OTHER = "OTHER",
}

export enum Degree {
  BTECH = "BTECH",
  BSC = "BSC",
  BE = "BE",
  BCA = "BCA",
  BSCHONS = "BSCHONS",
  BDES = "BDES",
  BPHIL = "BPHIL",
  MTECH = "MTECH",
  MSC = "MSC",
  ME = "ME",
  MCA = "MCA",
  MSR = "MSR",
  MBA = "MBA",
  MDES = "MDES",
  MPHIL = "MPHIL",
  PGDM = "PGDM",
  PHD = "PHD",
  DENG = "DENG",
}
